backend:
  name: github
  repo: hs3city/hs3.pl
  branch: main # Branch to update (optional; defaults to master)
  open_authoring: true
publish_mode: editorial_workflow # Enable review before integrating changes
media_folder: "/static/images/uploads" # Media files repo storage location
public_folder: "/images/uploads" # The src attribute for uploaded media
collections:
  - name: "projekty" # Used in routes, e.g., /admin/collections/blog
    label: "[PL] Projekty" # Used in the UI
    folder: "content/pl/projekty" # The path to the folder where the documents are stored
    media_folder: "/static/images/projekty" # The path to the folder where images are stored
    public_folder: "/images/projekty" # The src attribute for uploaded media
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
  - name: "projekty-en"
    label: "[ENG] Projects"
    folder: "content/en/projekty"
    media_folder: "/static/images/projekty"
    public_folder: "/images/projekty"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
  - name: "zasoby"
    label: "[PL] Zasoby"
    summary: "{{title}}"
    folder: "content/pl/zasoby"
    media_folder: "/static/images/zasoby"
    public_folder: "/images/projekty"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['commit_date', 'title', 'tags', 'category']
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: true
        options: 
          - dokumentacja
          - edukacja
          - grafika
          - hardware
          - outside-the-box
          - software
          - wydarzenia
        hint: "**Dokumentacja** dotyczy dokumentów, regulaminów i opisów, **edukacja** materiałów edukacyjnych, a **wydarzenia** tych związanych z eventami hs3. W **grafice** znajdziesz materiały graficzne i marketingowe. **Hardware** to urządzenia i narzędzia, a **software** oprogramowanie. **Outside-the-box** to kategoria dla osób, które nie chcą trzymać się schematów."
    view_groups:
      - label: "kategoria"
        field: "category"
  - name: "zasoby-en"
    label: "[ENG] Resources"
    folder: "content/en/zasoby"
    media_folder: "/static/images/zasoby"
    public_folder: "/images/projekty"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featureImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: true
        options: 
          - dokumentacja
          - edukacja
          - grafika
          - hardware
          - outside-the-box
          - software
          - wydarzenia
        hint: "**Dokumentacja** is for documents, rules and descriptions, **edukacja** is for educational materials, and **wydarzenia** for those connected with events in hs3. In **grafika** you can find graphic and marketing. **Hardware** are devices and tools and **software** is programs etc. **Out-of-the-box** is a category for people who think outside the box."
    view_groups:
      - label: "category"
        field: "category"
