name: Update Calendar

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run every 3 hours
  schedule:
    - cron: '0 */3 * * *'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'update'
  cancel-in-progress: false

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./automation/kronos
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Discord events
        working-directory: ./automation/kronos
        run: |
          python kronos.py
          if [ $? -ne 0 ]; then
            echo "Script failed with exit code $?"
            exit $?
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Sync Discord events
          branch: main
